groupName: cert-manager-webhook-spaceship.hjwylde.github.io

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/hjwylde/cert-manager-webhook-spaceship
  tag: "@sha256:5d6068b0cef38a7105df4a464f9d750a916de7fe2dd8b1a3f8d34d9e29bc595f"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
