groupName: cert-manager-webhook-spaceship.hjwylde.github.io

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/hjwylde/cert-manager-webhook-spaceship
  tag: "@sha256:22ab90e9d441e741e9665c3fe7bd22dabbe1bd65496b76fd75d4e91eed0244df"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
