groupName: cert-manager-webhook-spaceship.hjwylde.github.io

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/hjwylde/cert-manager-webhook-spaceship
  tag: "@sha256:dea5c6f9736ebc0c37d40fd97b1105e26f05f9d8ae9f61f24e724374bea22fdf"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
