name: Docker (Build and Publish)

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
    paths:
      - internal/**
      - Dockerfile
      - docker-bake.hcl
      - go.mod
      - go.sum
      - main.go
      - mise.toml
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4

      - name: Log into registry ghcr.io
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch,enable={{is_not_default_branch}}
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Run Docker Bake
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7
        with:
          source: .
          provenance: false
          sbom: false
          files: |
            docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
